<script type="text/javascript">


	function callbackFacebook() {

	    wsh.exec('_facebook -me', function(json) {
	    	
	    	setCookie("fb_user", JSON.stringify(json.data) );

    		wsh.exec('_facebook -me', function(json) {
				$.ajax({
					url: '/user/fbme',
					data: 'mail=' + json.data.email,
					success: function(data) {
						if (data == 'ok')
						{
							window.location.href = '/user/';
						}
						else
						{
							$('.signin, .home-slider, ').slideUp('fast')
							$('#register').slideDown('fast')
							$('#register_nom').val(json.data.last_name)
							$('#register_prenom').val(json.data.first_name)
							$('#register_date_birth').val(json.data.birthday)
							$('#register_mail').val(json.data.email)
						}
					}
				});
			});

    	});
	}

	$(document).ready(function() {
		$('#connect a').click(function() {
			wsh.exec('oauth -provider facebook', function(json) {
				$('body').append(json.view);
				syncSetCallback(callbackFacebook);
			});
			return false;
		});
	});

</script>

<div class="home">

	<div class="home-slider row">

		<div class="js-slider">
			<ul class="js-wrapper">
				<li class="slide">
					<img src="/img/slide-1.png" />
				</li>
				<li class="slide">
					<img src="/img/slide-2.png" />
				</li>
				<li class="slide">
					<img src="/img/slide-3.png" />
				</li>
				<li class="slide">
					<img src="/img/slide-4.png" />
				</li>
			</ul>
		</div>

		<div class="slider-nav">
			<a class="prev js-nav hide">prev</a>
			<a class="next js-nav">next</a>

			<ul class="js-bullets">
				<li class="bullet"></li>
				<li class="bullet"></li>
				<li class="bullet"></li>
				<li class="bullet"></li>
			</ul>
		</div>	

	</div>

	<div class="signin">
		<p><strong>TrainSpot</strong> vous permet d'échanger avec les voyageurs qui partagent votre trajet quotidien</p>
		<?php if( ! Zend_Auth::getInstance()->hasIdentity() ) : ?>
			<div id="connect" style="text-align: center; margin-top: 10px">
				<a href="#" class="btn btn-primary btn-large">
					Connectez vous avec Facebook
				</a>
			</div>
		<?php endif; ?>
	</div>

	<div id="register" style="display: none">
		<?php echo $this->partial('index/register.phtml'); ?>
	</div>
</div>