
<div class="container">
	
	Carousel de présentation de Jérôme et Ginette		

	<div class="home-slider row">

		<div class="js-slider">
			<ul class="js-wrapper">
				<li class="slide"><img src="http://placehold.it/960x600" /></li>
				<li class="slide"><img src="http://placehold.it/960x600" /></li>
				<li class="slide"><img src="http://placehold.it/960x600" /></li>
				<li class="slide"><img src="http://placehold.it/960x600" /></li>
			</ul>
		</div>

		<div class="slider-nav">
			<a class="prev js-nav">prev</a>
			<a class="next js-nav">next</a>

			<ul class="js-bullets">
				<li class="bullet"></li>
				<li class="bullet"></li>
				<li class="bullet"></li>
				<li class="bullet"></li>
			</ul>
		</div>	

	</div>

	<p style="">
		C'est parti :
		<a id="connect">
			<img src="/img/fbconnect.png" alt="facebook connect"/>
		</a>
	</p>

</div>
