

<div class="container">
<form class="form-horizontal js-setup" action="/user/register" method="POST" name="register_form">
    <fieldset class="row">
	    <legend>S'inscrire</legend>

	    <div class="control-group">
		    <label class="control-label" for="register_prenom">Prénom&nbsp;:</label>
		    <div class="controls">
				<input type="text" class="span3" name="prenom" id="register_prenom" value="<?php echo $this->prenom; ?>" />
		    </div>
	    </div>

	    <div class="control-group">
		    <label class="control-label" for="register_nom">Nom&nbsp;:</label>
		    <div class="controls">
				<input type="text" class="span3" name="nom" id="register_nom" value="<?php echo $this->nom; ?>" />
		    </div>
	    </div>

	    <div class="control-group">
		    <label class="control-label" for="register_mail">Email&nbsp;:</label>
		    <div class="controls">
				<input type="text" class="span3" name="mail" id="register_mail" value="<?php echo $this->email; ?>" />
		    </div>
	    </div>

	    <div class="control-group">
		    <label class="control-label" for="register_date_birth">Date de naissance&nbsp;:</label>
		    <div class="controls">
				<input type="text" class="span3" name="ddn" id="register_date_birth" value="<?php echo $this->ddn; ?>" />
		    </div>
	    </div>

	    <div class="form-actions">
	    	<button class="btn btn-primary" type="submit">Suivant</button>
	    </div>

	</fieldset>
</form>
</div>