<!doctype html>
<!--[if lt IE 7]> <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>

        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width,initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

        
        <meta name="description" content="" />
	   
        <meta name="keywords" content="" />
        <link rel="canonical" href="" />

        <title>Trainspot</title>

        <link href='http://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>

        <link href="/css/bootstrap.min.css" rel="stylesheet">   
        <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">                    
        <link href="/css/jquery-ui-1.8.16.custom.css" rel="stylesheet">      
        <link href="/css/jquery.ui.1.8.16.ie.css" rel="stylesheet">      
        <link href="/less/style.less" rel="stylesheet/less" type="text/css">     

        <!-- Le fav and touch icons -->
        <link rel="shortcut icon" href="">

        <meta property="og:title" content="{$smarty.const.SITE_DESCRIPTION}" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="{$smarty.const.SITE_URL}" />
        <meta property="og:site_name" content="{$smarty.const.SITE_TITLE}" />
        <meta property="fb:admins" content="{$smarty.const.SITE_FB_ADMIN}" />
        
        <meta property="og:image" content="" />
        <link rel="image_src" type="image/jpeg" href="" />

    </head>

    <body>
                
        <div id="fb-root"></div>

	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
	      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/js/jquery.min.js"><\/script>')</script>

	<script type="text/javascript" src="http://webshell.io/api/js?key=47844ded8999967dae45662d1e8c449a"></script>
        <script src="/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/js/less.min.js" type="text/javascript"></script>

        <script src="/js/iScroll.class.js" type="text/javascript"></script>    
        <script src="/js/jquery.scrollTo-min.js" type="text/javascript"></script>    
        <script src="/js/jquery.uSlide.js" type="text/javascript"></script>    

        <script src="/js/less.min.js" type="text/javascript"></script>
        <script src="/js/jquery-ui-1.8.16.custom.min.js" type="text/javascript"></script>    
        
        <script src="/js/Modernizr.class.js" type="text/javascript"></script>
        <script src="/js/functions.utils.js" type="text/javascript"></script>
        <script src="/js/global.js" type="text/javascript"></script>

        <script>
            var _gaq=[['_setAccount','UA-'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>

        <?php $controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?>

        <?php if( Zend_Auth::getInstance()->hasIdentity() ) : ?>

            <div class="pull-right dropdown" id="user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-user"></i> <?= Zend_Auth::getInstance()->getIdentity()->firstname ?>
                    <b class="caret"></b>
                </a>

                <ul class="dropdown-menu">
                    <li><a href="/user">Tableau de bord</a></li>
                    <li class="divider"></li>
                    <li><a href="/user/trajet">Mes trajets</a></li>
                    <li><a href="/user/interest">Mes intérêts</a></li>
                    <li><a href="/user/matching">Mes rencontres</a></li>
                    <li class="divider"></li>
                    <li><a href="/user/signout">Déconnexion</a></li>
                </ul>
            </div>

        <?php endif; ?>


        <?php if( $controllerName == "index" ) : ?>

           <header>
                <h1><img alt="Trainspot" src="/img/logo-grd.png" /></h1>
                <h2>PARTAGER PLUS QUE VOTRE TRAJET</h2>
            </header>

        <?php else: ?>

            <header class="mini">
                <h1><a href="/"><img alt="Trainspot" src="/img/logo-pti.png" /></a></h1>
            </header>

        <?php endif; ?> 


        <?php echo $this->layout()->content; ?>

        <footer class="container">
            <div class="pull-right">
                <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
                <script>
                new TWTR.Widget({
                  version: 2,
                  type: 'search',
                  search: '@_trainspot_',
                  interval: 30000,
                  title: '',
                  subject: '@_TrainSpot_',
                  width: 250,
                  height: 150,
                  theme: {
                    shell: {
                      background: '#991358',
                      color: '#ffffff'
                    },
                    tweets: {
                      background: '#ffffff',
                      color: '#444444',
                      links: '#991358'
                    }
                  },
                  features: {
                    scrollbar: false,
                    loop: false,
                    live: true,
                    behavior: 'all'
                  }
                }).render().start();
                </script>
            </div>
        </footer>

    </body>
</html>
