<!doctype html>
<!--[if lt IE 7]> <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>

        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
	    <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

        
        <meta name="description" content="" />
	   
        <meta name="keywords" content="" />
        <link rel="canonical" href="" />

        <title>Trainspot</title>

        <link href="/css/bootstrap.css" rel="stylesheet">                    
        <link href="/css/jquery-ui-1.8.16.custom.css" rel="stylesheet">      
        <link href="/css/jquery.ui.1.8.16.ie.css" rel="stylesheet">      
        <link href="/less/style.less" rel="stylesheet/less" type="text/css">     

        <!-- Le fav and touch icons -->
        <link rel="shortcut icon" href="">

        <meta property="og:title" content="{$smarty.const.SITE_DESCRIPTION}" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="{$smarty.const.SITE_URL}" />
        <meta property="og:site_name" content="{$smarty.const.SITE_TITLE}" />
        <meta property="fb:admins" content="{$smarty.const.SITE_FB_ADMIN}" />
        
        <meta property="og:image" content="" />
        <link rel="image_src" type="image/jpeg" href="" />

    </head>

    <body>
                
        <div id="fb-root"></div>

		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	    <!--[if lt IE 9]>
	      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	    <![endif]-->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/js/jquery.min.js"><\/script>')</script>

		<script type="text/javascript" src="http://webshell.io/api/js?key=47844ded8999967dae45662d1e8c449a"></script>
        <script src="/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/js/less.min.js" type="text/javascript"></script>

        <script src="/js/iScroll.class.js" type="text/javascript"></script>    
        <script src="/js/jquery.scrollTo-min.js" type="text/javascript"></script>    
        <script src="/js/jquery.µSlide.js" type="text/javascript"></script>    

        <script src="/js/less.min.js" type="text/javascript"></script>
        <script src="/js/jquery-ui-1.8.16.custom.min.js" type="text/javascript"></script>    
        
        <script src="/js/Modernizr.class.js" type="text/javascript"></script>
        <script src="/js/global.js" type="text/javascript"></script>

        <script>
            var _gaq=[['_setAccount','UA-'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>

        <?php echo $this->layout()->content; ?>

    </body>
</html>
