<script type="text/javascript">
$(document).ready(function() {
	$('#contact-form').submit(function() {
		var data = $(this).serialize();
		$.ajax({
			url: '/user/contact',
			type: 'post',
			data: data,
			success: function(data) {
				if (data == 'ok')
				{
					alert('Message envoyé');
					window.location.href = '/user';
				}
				else
					alert('Erreur : message non envoyé');
			}
		})
	});
})
</script>
<div style="width: 80%; margin-left: 10%;">
	<h1>Contacter l'utilisateur par SMS</h1>
	<form id="contact-form" action="#">
		<input type="hidden" name="id" value="<?php echo $this->iduser; ?>" />
		<textarea onkeyup="this.value = this.value.slice(0, 140)" onchange="this.value = this.value.slice(0, 140)" name="message" style="width: 50%; height: 100px"><?php echo Zend_Auth::getInstance()->getIdentity()->firstname . ' ' . Zend_Auth::getInstance()->getIdentity()->lastname; ?> aimerait vous rencontrer pour : <?php echo $this->theme ?> à <?php echo $this->gare; ?>

--
tel: <?php echo Zend_Auth::getInstance()->getIdentity()->phone; ?></textarea>
		<button>Envoyer</button>
	</form>	
</div>