<div class="container">
	<form class="form-horizontal js-interest" method="POST">
	    <fieldset class="row">
		    <legend>Définir ses intérêts</legend>

		    <div class="span6">

			    <div class="control-group">
				    <label class="control-label" for="your-need">Vous cherchez&nbsp;:</label>
				    
				    <div class="controls">
					    <select class="span3 domain" id="your-need" name="your-need">						    		
					    	<option value="-1">Dans le domaine...</option>
					    	<option data-placeholder="Une conversation en espagnol" value="jeu">Jeu</option>
					    	<option data-placeholder="Une expérience du canada" value="langue">Langue</option>
					    	<option data-placeholder="Un cours rapide de tricot" value="voyage">Voyage</option>
					    	<option data-placeholder="Une partie de crapette" value="initiation">Initiation</option>
					    	<option data-placeholder="Une recette" value="recette">Recette</option>
					    	<option data-placeholder="Découvrir le métier de physicien" value="experience">Expérience profesionnelle</option>
					    </select>
				    </div>
			    </div>

			    <div id="need-container" class="controls hide js-need content">
			    	<input type="text" class="text span3" id="your-need-input" name="content-need" />
			    </div>

			    <ul class="my-interests unstyled">
			    	<?php foreach ($this->needs as $need): ?>
			    	<li><img src="/img/pic-need.png" class="" /><?php echo '<strong>' . $need['title'] . '</strong> : ' . $need['desc']; ?></li>
				    <?php endforeach; ?>
			    </ul>

			</div>

		    <div class="span6">

			    <div class="control-group">
				    <label class="control-label" for="your-proposal">Vous proposez&nbsp;:</label>
				    
				    <div class="controls">
					    <select class="span3 domain" id="your-proposal" name="your-proposal">		    		
					    	<option value="-1">Dans le domaine...</option>
					    	<option data-placeholder="Une conversation en espagnol" value="jeu">Jeu</option>
					    	<option data-placeholder="Une expérience du canada" value="langue">Langue</option>
					    	<option data-placeholder="Un cours rapide de tricot" value="voyage">Voyage</option>
					    	<option data-placeholder="Une partie de crapette" value="initiation">Initiation</option>
					    	<option data-placeholder="Une recette" value="recette">Recette</option>
					    	<option data-placeholder="Découvrir le métier de physicien" value="experience">Expérience profesionnelle</option>
					    </select>
				    </div>
			    </div>

			    <div class="control-group">
				    
				    <div id="proposal-container" class="controls hide js-proposal content">
				    	<input type="text" class="text span3" id="your-proposal-input" name="content-proposal" />
				    </div>

			    <ul class="my-interests unstyled">
			    	<?php foreach ($this->proposals as $proposal): ?>
			    	<li><img src="/img/pic-want.png" class="" /><?php echo '<strong>' . $proposal['title'] . '</strong> : ' . $proposal['desc']; ?></li>
				    <?php endforeach; ?>
			    </ul>

			    </div>

			</div>


	    </fieldset>

	    <div class="form-actions">
	    	<button class="btn btn-primary" type="submit">Connectez vous avec Facebook</button>
	    	<a class="btn" href="/user/trajet">Revenir aux trajets</a>
	    </div>
	</form>
</div>