<div class="container">
	<form class="form-horizontal js-interest" method="POST">
	    <fieldset class="row">
		    <legend>Définir ses intérêts</legend>

		    <div class="span6">

		    	<h2><label for="your-need">Je cherche</label></h2>

			    <p class="note">
			    	Faites comme Martin, <br />
			    	cherchez des conversations en anglais
			    </p>

			    <select class="span3 domain" id="your-need" name="your-need">						    		
			    	<option value="-1">Dans le domaine...</option>
			    	<option data-placeholder="Une conversation en espagnol" value="langue">Langue</option>
			    	<option data-placeholder="Une expérience du canada" value="voyage">Voyage</option>
			    	<option data-placeholder="Une partie de crapette" value="jeu">Jeu</option>
			    	<option data-placeholder="Un cours rapide de tricot" value="initiation">Initiation</option>
			    	<option data-placeholder="Une recette" value="recette">Recette</option>
			    	<option data-placeholder="Découvrir le métier de physicien" value="experience">Expérience profesionnelle</option>
			    </select>

			    <div id="need-container" class="hide js-need content">
			    	<input type="text" class="text span3" id="your-need-input" name="content-need" />
			    </div>

			    <ul class="my-interests unstyled">
			    	<?php foreach ($this->needs as $need): ?>
			    	<li><img src="http://placehold.it/30x25" class="" /><?php echo '<strong>' . $need['title'] . '</strong> : ' . $need['desc']; ?></li>
				    <?php endforeach; ?>
			    </ul>

			</div>

		    <div class="span6">

			    <h2><label for="your-proposal">Je propose</label></h2>
			    
			    <p class="note">
			    	Faites comme Annabelle, <br />
			    	proposez votre expérience du Canada
			    </p>

			    <select class="span3 domain" id="your-proposal" name="your-proposal">		    		
			    	<option value="-1">Dans le domaine...</option>
			    	<option data-placeholder="Une conversation en espagnol" value="langue">Langue</option>
			    	<option data-placeholder="Une expérience du canada" value="voyage">Voyage</option>
			    	<option data-placeholder="Une partie de crapette" value="jeu">Jeu</option>
			    	<option data-placeholder="Un cours rapide de tricot" value="initiation">Initiation</option>
			    	<option data-placeholder="Une recette" value="recette">Recette</option>
			    	<option data-placeholder="Découvrir le métier de physicien" value="experience">Expérience profesionnelle</option>
			    </select>

			    <div id="proposal-container" class="hide js-proposal content">
			    	<input type="text" class="text span3" id="your-proposal-input" name="content-proposal" />
			    </div>


			</div>


			<div class="span12">
				<button class="submit OK" type="submit">OK</button>
			</div>

	    </fieldset>


	</form>
</div>