<div class="container">

	<div class="matching">

		<?php $i = 0; ?>
		<?php foreach($this->results as $result): ?>

			<?php foreach ($result['interest'] as $interest): ?>

				<div class="line">
					<div class="row">
						<div class="span3">
							<?php echo $result['user']['firstname'] . ' ' . $result['user']['lastname']; ?>
						</div>

						<div class="span3">
							<?php 
								echo $interest['need_proposal'] == 0 ? 
									'<img src="/img/pic-want.png" />Propose'
									: 

									'<img src="/img/pic-need.png" />Recherche';
							?>
						</div>
								
						<div class="span2">
							<?php echo 'Rencontre à ' . $result['gare_rencontre'][0]; ?>
						</div>

						<div class="span2">
							<strong><?php echo $interest['title'] . '</strong> : ' . $interest['desc']; ?>
						</div>

						<div class="span1">
							<a style="color: inherit; text-decoration: none;" 
					   		   href="/user/contact?id=<?php echo $result['user']['id_user'] ?>&theme=<?php echo urlencode($interest['title'] . ' : ' . $interest['desc']); ?>&gare=<?php echo urlencode($result['gare_rencontre'][0]); ?>">
					   		   contact
					   		</a>
						</div>
					</div>
				</div>
			
			<?php endforeach; ?>

		<?php endforeach; ?>

	</div>

</div>